const employees = [
    {
        id: "0123105",
        name: "سعد علي سعد القرني",
        nationalId: "1050789732",
        email: "saadaa@moh.gov.sa",
        mobile: "966542285582",
        nationality: "سعودي",
        qualification: "دبلوم",
        jobTitle: "رئيس قسم المختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "14/04/1426",
        currentDate: "14/04/1426",
        avatar: "https://ui-avatars.com/api/?name=سعد+القرني&background=0D8ABC&color=fff"
    },
    {
        id: "7219250",
        name: "مسفر عائض محمد القرني",
        nationalId: "1050495330",
        email: "mealqarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "غير محدد",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "29/02/1428",
        currentDate: "29/02/1428",
        avatar: "https://ui-avatars.com/api/?name=مسفر+القرني&background=random"
    },
    {
        id: "0123124",
        name: "محمد دخيل الله محمد الغامدي",
        nationalId: "1046970354",
        email: "malghamdi105@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "ماجستير",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "22/10/1430",
        currentDate: "22/10/1430",
        avatar: "https://ui-avatars.com/api/?name=محمد+الغامدي&background=random"
    },
    {
        id: "65269",
        name: "محمد خلف أحمد الخثعمي",
        nationalId: "1067842144",
        email: "malkth@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم ثلاث سنوات بعد الثانوي",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "10/03/1436",
        currentDate: "10/03/1436",
        avatar: "https://ui-avatars.com/api/?name=محمد+الخثعمي&background=random"
    },
    {
        id: "7221400",
        name: "محمد سهلان سعد العلياني",
        nationalId: "1054148430",
        email: "moalaryani@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم الكلية الصحية",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "17/03/1429",
        currentDate: "17/03/1429",
        avatar: "https://ui-avatars.com/api/?name=محمد+العلياني&background=random"
    },
    {
        id: "46139",
        name: "فهد عبدالله محمد القرني",
        nationalId: "1047032600",
        email: "falqarni2@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم ثلاث سنوات ونصف بعد الثانوي",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "29/08/1434",
        currentDate: "29/08/1434",
        avatar: "https://ui-avatars.com/api/?name=فهد+القرني&background=random"
    },
    {
        id: "0123074",
        name: "سلطان محمد دخيل القرني",
        nationalId: "1073824862",
        email: "sumoalqarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "بكالوريوس",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "22/10/1430",
        currentDate: "22/10/1430",
        avatar: "https://ui-avatars.com/api/?name=سلطان+القرني&background=random"
    },
    {
        id: "0124959",
        name: "محمد سعد عبدالله القرني",
        nationalId: "1063751299",
        email: "malqarni3@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم ثلاث سنوات ونصف بعد الثانوي",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "19/04/1431",
        currentDate: "19/04/1431",
        avatar: "https://ui-avatars.com/api/?name=محمد+القرني&background=random"
    },
    {
        id: "7241475",
        name: "نايف عبدالله محبوب القرني",
        nationalId: "1048612038",
        email: "naaalgarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "28/12/1433",
        currentDate: "28/12/1433",
        avatar: "https://ui-avatars.com/api/?name=نايف+القرني&background=random"
    },
    {
        id: "7245417",
        name: "حاتم خليفة كرار",
        nationalId: "2346751742",
        email: "hbala@moh.gov.sa",
        mobile: "",
        nationality: "سوداني",
        qualification: "Fellowship",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "18/07/1434",
        currentDate: "18/07/1434",
        avatar: "https://ui-avatars.com/api/?name=حاتم+كرار&background=random"
    },
    {
        id: "7707014",
        name: "سعد عيد سعيد ال سعد القرني",
        nationalId: "1024174219",
        email: "sealgarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "بكالوريوس",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "14/04/1426",
        currentDate: "14/04/1426",
        avatar: "https://ui-avatars.com/api/?name=سعد+القرني+2&background=random"
    },
    {
        id: "66540",
        name: "حسام سعيد عبدالله القرني",
        nationalId: "1063191553",
        email: "halgarny@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم ثلاث سنوات بعد الثانوي",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "10/03/1436",
        currentDate: "10/03/1436",
        avatar: "https://ui-avatars.com/api/?name=حسام+القرني&background=random"
    },
    {
        id: "7221389",
        name: "محمد ناصر محمد القرني",
        nationalId: "1024169334",
        email: "moalqarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "بكالوريوس",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "17/03/1429",
        currentDate: "17/03/1429",
        avatar: "https://ui-avatars.com/api/?name=محمد+ناصر&background=random"
    },
    {
        id: "0131662",
        name: "عبدالرحمن صالح عبدالرحمن القرني",
        nationalId: "1065836031",
        email: "moalaryani@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "ماجستير",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "17/03/1429",
        currentDate: "17/03/1429",
        avatar: "https://ui-avatars.com/api/?name=عبدالرحمن+القرني&background=random"
    },
    {
        id: "7670327",
        name: "بدر محمد ماكن القرني",
        nationalId: "1065526806",
        email: "BaMAlqarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم الكلية الصحية",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "02/02/1440",
        currentDate: "02/02/1440",
        avatar: "https://ui-avatars.com/api/?name=بدر+القرني&background=random"
    },
    {
        id: "7669825",
        name: "عبدالعزيز راشد جديع البريدي",
        nationalId: "1068877495",
        email: "aralbaradi@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "بكالوريوس",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "22/04/1439",
        currentDate: "22/04/1439",
        avatar: "https://ui-avatars.com/api/?name=عبدالعزيز+البريدي&background=random"
    },
    {
        id: "7670350",
        name: "منصور محمد منصور القرني",
        nationalId: "1079644991",
        email: "mealqarni@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم الكلية الصحية",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "29/02/1428",
        currentDate: "29/02/1428",
        avatar: "https://ui-avatars.com/api/?name=منصور+القرني&background=random"
    },
    {
        id: "7670368",
        name: "نايف محمد عبدالله العلياني",
        nationalId: "1076580677",
        email: "moalaryani@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "17/03/1429",
        currentDate: "17/03/1429",
        avatar: "https://ui-avatars.com/api/?name=نايف+العلياني&background=random"
    },
    {
        id: "62526",
        name: "محمد صالح محمد الخثعمي",
        nationalId: "1047908130",
        email: "malkth@moh.gov.sa",
        mobile: "",
        nationality: "سعودي",
        qualification: "دبلوم ثلاث سنوات بعد الثانوي",
        jobTitle: "فني مختبر",
        department: "تجمع عسير الصحي - نطاق بيشة - مستشفى سبت العلايا العام - إدارة الخدمات الطبية المساندة - قسم المختبر",
        startDate: "10/03/1436",
        currentDate: "10/03/1436",
        avatar: "https://ui-avatars.com/api/?name=محمد+صالح&background=random"
    }
];
